platform :ios, '13.0'
use_frameworks!

require_relative '../OpenTokSDKVersion'

target 'Media-Transformers' do
  pod 'OTXCFramework', OpenTokSDKVersion
  pod 'VonageClientSDKVideoTransformers' , OpenTokSDKVersion
end
